export const testData = [
  {
    id: "node_1",
    x: 400,
    y: 500,
    label: "node1",
    zIndex: 1,
  },
  {
    id: "node_2",
    parentId: "node_1",
    x: 550,
    y: 500,
    label: "node2",
    zIndex: 1,
  },
  {
    id: "node_3",
    parentId: "node_2",
    x: 700,
    y: 400,
    label: "node3",
    zIndex: 1,
  },
  {
    id: "node_4",
    parentId: "node_2",
    x: 700,
    y: 600,
    label: "node4",
    zIndex: 1,
  },
];

export const testData2 = [
  {
    id: "node_1",
    x: 76,
    y: 487,
    label: "asdsadasdsadasdsadasdasdhenadsad",
    zIndex: 2,
  },
  {
    id: "node_2",
    parentId: "node_1",
    x: 382,
    y: 487,
    label: "mingzihenchangaaaaaaaadasdsd",
    zIndex: 1,
  },
  {
    id: "node_3",
    parentId: "node_2",
    x: 656,
    y: 237,
    label: "node3",
    zIndex: 2,
  },
  {
    id: "node_4",
    parentId: "node_2",
    x: 656,
    y: 537,
    label: "node4",
    zIndex: 1,
  },
  {
    x: 746,
    y: 87,
    zIndex: 1,
    parentId: "node_3",
    label: "new node",
    id: "node_5",
  },
  {
    x: 860,
    y: 187,
    zIndex: 1,
    parentId: "node_18",
    label: "new node",
    id: "node_6",
  },
  {
    x: 656,
    y: 337,
    zIndex: 1,
    parentId: "node_2",
    label: "new node",
    id: "node_9",
  },
  {
    x: 656,
    y: 437,
    zIndex: 1,
    parentId: "node_2",
    label: "new node",
    id: "node_10",
  },
  {
    x: 656,
    y: 637,
    zIndex: 1,
    parentId: "node_2",
    label: "new node",
    id: "node_14",
  },
  {
    x: 656,
    y: 737,
    zIndex: 1,
    parentId: "node_2",
    label: "new node",
    id: "node_15",
  },
  {
    x: 746,
    y: 287,
    zIndex: 1,
    parentId: "node_3",
    label: "new node",
    id: "node_16",
  },
  {
    x: 746,
    y: 387,
    zIndex: 1,
    parentId: "node_3",
    label: "new node",
    id: "node_17",
  },
  {
    x: 746,
    y: 187,
    zIndex: 2,
    label: "new node",
    id: "node_18",
    parentId: "node_3",
  },
  {
    x: 746,
    y: 487,
    zIndex: 1,
    parentId: "node_4",
    label: "new node",
    id: "node_19",
  },
  {
    x: 746,
    y: 587,
    zIndex: 1,
    parentId: "node_4",
    label: "new node",
    id: "node_20",
  },
  {
    x: 860,
    y: 487,
    zIndex: 1,
    parentId: "node_19",
    label: "new node",
    id: "node_21",
  },
  {
    x: 860,
    y: 537,
    zIndex: 1,
    parentId: "node_20",
    label: "new node",
    id: "node_22",
  },
  {
    x: 860,
    y: 637,
    zIndex: 1,
    parentId: "node_20",
    label: "new node",
    id: "node_23",
  },
  {
    x: 974,
    y: 537,
    zIndex: 1,
    parentId: "node_22",
    label: "new node",
    id: "node_24",
  },
  {
    x: 1088,
    y: 537,
    zIndex: 1,
    parentId: "node_24",
    label: "new node",
    id: "node_25",
  },
];
